CFLAG=-Wall -g

all: clean normaldata enum struct union class oneDimension twoDimension

normaldata: normaldata

enum: enum

struct: struct

union: union

class: class

oneDimension: oneDimension

twoDimension: twoDimension

clean:
	rm -rf normaldata
	rm -rf enum
	rm -f union
	rm -rf struct
	rm -rf class
	rm -f oneDimension
	rm -f twoDimension
