-- Test Case Script
TEST.UNIT:Unit
TEST.SUBPROGRAM:function_1
TEST.NEW
TEST.NAME:Unit_function_1.001
TEST.VALUE:z:3
TEST.END


-- Test Case Script
TEST.UNIT:UnitB
TEST.SUBPROGRAM:functionB
TEST.NEW
TEST.NAME:Unit_functionB.001
TEST.VALUE:y:2
TEST.END
--

-- Test Case Script
TEST.UNIT:Unit
TEST.SUBPROGRAM:function_1
TEST.NEW
TEST.NAME:Unit_function_1.002
TEST.VALUE:x:1
TEST.END
--

-- Test Case Script
TEST.UNIT:UnitB
TEST.SUBPROGRAM:function_1
TEST.NEW
TEST.NAME:B.f1.002
TEST.VALUE:a:1000
TEST.END
TEST.SUBPROGRAM:function_2
TEST.NEW
TEST.NAME:B.f2.001
TEST.VALUE:a:1000
TEST.END
--


TEST.SUBPROGRAM:<<COMPOUND>>
TEST.NEW
TEST.NAME:<<COMPOUND>>.001
TEST.VALUE:a:100999
TEST.END