package com.dse.guifx_v3.objects;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

/**
 * Represent the table below the table of test cases generated by AUTOMATED TEST DATA GENERATION
 */
public class TestCaseExecutionDataNode {
    private int id;
    private String name;
    private String value;
    private String coverage;
    private String unvisited;
    private ObservableList<String> detail = FXCollections.observableArrayList();

    public TestCaseExecutionDataNode() {}

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * We should not display full value on GUI.
     * The long length may lead to low performance when interacting with test case execution tab.
     *
     * @return
     */
    public String getShortenValue() {
        int MAX_LENGTH = 50;
        if (value.length() > MAX_LENGTH)
            return value.substring(0, MAX_LENGTH) + "...";
        else
            return value;
    }
    public String getValue() {
        return value;
    }
    public String getCoverage() {
        return coverage;
    }

    public ObservableList<String> getDetail() {
        return detail;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public void setCoverage(String coverage) {
        this.coverage = coverage;
    }

    public String getUnvisited() {
        return unvisited;
    }

    public void setUnvisited(String unvisited) {
        this.unvisited = unvisited;
    }
}
